# Generated by Django 5.2.2 on 2025-06-05 13:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Create Time')),
                ('modify_time', models.DateTimeField(auto_now=True, verbose_name='Modify Time')),
                ('title', models.CharField(max_length=255, verbose_name='subject')),
                ('description', models.TextField(max_length=20000, verbose_name='description')),
                ('template_type', models.PositiveSmallIntegerField(choices=[(0, 'SYSTEM'), (1, 'SMS'), (2, 'EMAIL')], verbose_name='application service type')),
            ],
            options={
                'verbose_name': 'Notification Template',
                'verbose_name_plural': 'Notification Templates',
            },
        ),
        migrations.CreateModel(
            name='EmailNotification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Create Time')),
                ('modify_time', models.DateTimeField(auto_now=True, verbose_name='Modify Time')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('description', models.TextField(max_length=10000, verbose_name='description')),
                ('event_time', models.DateTimeField(blank=True, null=True, verbose_name='event time')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='is deleted')),
                ('source', models.CharField(blank=True, max_length=255, null=True, verbose_name='source of template notification')),
                ('priority', models.PositiveSmallIntegerField(choices=[(0, 'LOW'), (1, 'MEDIUM'), (2, 'HIGH'), (3, 'CRITICAL')], verbose_name='application priority type')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='received_emails', to=settings.AUTH_USER_MODEL, verbose_name='receiver')),
            ],
            options={
                'verbose_name': 'Email Notification',
                'verbose_name_plural': 'Email Notifications',
            },
        ),
        migrations.CreateModel(
            name='SMSNotification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Create Time')),
                ('modify_time', models.DateTimeField(auto_now=True, verbose_name='Modify Time')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('description', models.TextField(max_length=10000, verbose_name='description')),
                ('event_time', models.DateTimeField(blank=True, null=True, verbose_name='event time')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='is deleted')),
                ('source', models.CharField(blank=True, max_length=255, null=True, verbose_name='source of template notification')),
                ('priority', models.PositiveSmallIntegerField(choices=[(0, 'LOW'), (1, 'MEDIUM'), (2, 'HIGH'), (3, 'CRITICAL')], verbose_name='application priority type')),
                ('phone_number', models.CharField(max_length=16, verbose_name='phone number')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='received_sms', to=settings.AUTH_USER_MODEL, verbose_name='receiver')),
            ],
            options={
                'verbose_name': 'Sms Notification',
                'verbose_name_plural': 'Sms Notifications',
            },
        ),
        migrations.CreateModel(
            name='SystemNotification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Create Time')),
                ('modify_time', models.DateTimeField(auto_now=True, verbose_name='Modify Time')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('description', models.TextField(max_length=10000, verbose_name='description')),
                ('event_time', models.DateTimeField(blank=True, null=True, verbose_name='event time')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='is deleted')),
                ('source', models.CharField(blank=True, max_length=255, null=True, verbose_name='source of template notification')),
                ('priority', models.PositiveSmallIntegerField(choices=[(0, 'LOW'), (1, 'MEDIUM'), (2, 'HIGH'), (3, 'CRITICAL')], verbose_name='application priority type')),
                ('is_viewed', models.BooleanField(default=False, verbose_name='viewed by user')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='received_system_notifications', to=settings.AUTH_USER_MODEL, verbose_name='receiver')),
            ],
            options={
                'verbose_name': 'System Notification',
                'verbose_name_plural': 'System Notifications',
                'ordering': ('is_viewed',),
            },
        ),
    ]
