# Generated by Django 5.2.2 on 2025-06-06 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification_service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationpreference',
            name='entity_type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Company'), (1, 'Camera')], verbose_name='Entity type'),
        ),
    ]
