# Generated by Django 5.2.2 on 2025-06-05 13:38

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification_service', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Create Time')),
                ('modify_time', models.DateTimeField(auto_now=True, verbose_name='Modify Time')),
                ('event_type', models.CharField(max_length=50, verbose_name='event type')),
                ('details', models.JSONField(default=dict, verbose_name='details')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='events timestamp')),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
            },
        ),
        migrations.AlterModelOptions(
            name='emailnotification',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Email Notification', 'verbose_name_plural': 'Email Notifications'},
        ),
        migrations.AlterModelOptions(
            name='smsnotification',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Sms Notification', 'verbose_name_plural': 'Sms Notifications'},
        ),
        migrations.AlterModelOptions(
            name='systemnotification',
            options={'ordering': ['-timestamp'], 'verbose_name': 'System Notification', 'verbose_name_plural': 'System Notifications'},
        ),
        migrations.RemoveField(
            model_name='emailnotification',
            name='event_time',
        ),
        migrations.RemoveField(
            model_name='smsnotification',
            name='event_time',
        ),
        migrations.RemoveField(
            model_name='systemnotification',
            name='event_time',
        ),
        migrations.AddField(
            model_name='emailnotification',
            name='is_viewed',
            field=models.BooleanField(default=False, verbose_name='viewed by user'),
        ),
        migrations.AddField(
            model_name='emailnotification',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='timestamp'),
        ),
        migrations.AddField(
            model_name='smsnotification',
            name='is_viewed',
            field=models.BooleanField(default=False, verbose_name='viewed by user'),
        ),
        migrations.AddField(
            model_name='smsnotification',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='timestamp'),
        ),
        migrations.AddField(
            model_name='systemnotification',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='timestamp'),
        ),
        migrations.AddField(
            model_name='emailnotification',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='notification_service.event'),
        ),
        migrations.AddField(
            model_name='smsnotification',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='notification_service.event'),
        ),
        migrations.AddField(
            model_name='systemnotification',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='notification_service.event'),
        ),
        migrations.AddIndex(
            model_name='emailnotification',
            index=models.Index(fields=['receiver', 'is_viewed', 'priority'], name='notificatio_receive_4a55dc_idx'),
        ),
        migrations.AddIndex(
            model_name='emailnotification',
            index=models.Index(fields=['timestamp'], name='notificatio_timesta_aa39e7_idx'),
        ),
        migrations.AddIndex(
            model_name='smsnotification',
            index=models.Index(fields=['receiver', 'is_viewed', 'priority'], name='notificatio_receive_bc6470_idx'),
        ),
        migrations.AddIndex(
            model_name='smsnotification',
            index=models.Index(fields=['timestamp'], name='notificatio_timesta_b83408_idx'),
        ),
        migrations.AddIndex(
            model_name='systemnotification',
            index=models.Index(fields=['receiver', 'is_viewed', 'priority'], name='notificatio_receive_95411a_idx'),
        ),
        migrations.AddIndex(
            model_name='systemnotification',
            index=models.Index(fields=['timestamp'], name='notificatio_timesta_14a417_idx'),
        ),
    ]
