# Generated by Django 4.2.22 on 2025-06-07 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification_service', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailnotification',
            name='is_type_enabled',
            field=models.BooleanField(default=False, verbose_name='is type enabled for the user'),
        ),
        migrations.AddField(
            model_name='smsnotification',
            name='is_type_enabled',
            field=models.BooleanField(default=False, verbose_name='is type enabled for the user'),
        ),
        migrations.AddField(
            model_name='systemnotification',
            name='is_type_enabled',
            field=models.BooleanField(default=False, verbose_name='is type enabled for the user'),
        ),
    ]
