# Generated by Django 5.2.2 on 2025-06-06 20:23

import django.contrib.postgres.indexes
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0008_alter_user_phone_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Create Time')),
                ('modify_time', models.DateTimeField(auto_now=True, verbose_name='Modify Time')),
                ('name', models.CharField(max_length=255, verbose_name='Camera Name')),
                ('location', models.CharField(blank=True, max_length=255, null=True, verbose_name='Location')),
                ('ip_address', models.GenericIPAddressField(protocol='IPv4', unique=True, verbose_name='IP Address')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'ONLINE'), (1, 'OFFLINE')], db_index=True, verbose_name='status')),
                ('recording_status', models.PositiveSmallIntegerField(choices=[(0, 'Recording'), (1, 'Stopped')], db_index=True, verbose_name='recording status')),
                ('is_moved', models.BooleanField(db_index=True, default=False, verbose_name='is moved')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cameras', to='users.company', verbose_name='Company')),
            ],
            options={
                'verbose_name': 'Camera',
                'verbose_name_plural': 'Cameras',
            },
        ),
        migrations.CreateModel(
            name='CameraActionLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Create Time')),
                ('modify_time', models.DateTimeField(auto_now=True, verbose_name='Modify Time')),
                ('action', models.PositiveSmallIntegerField(choices=[(0, 'TURNED OFF'), (1, 'TURNED ON'), (2, 'MOVED'), (3, 'STARTED RECORDING'), (4, 'STOPPED RECORDING')], db_index=True, verbose_name='action')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='timestamp')),
                ('metadata', models.JSONField(default=dict, verbose_name='metadata')),
                ('old_status', models.CharField(blank=True, max_length=20, null=True, verbose_name='old status')),
                ('new_status', models.CharField(blank=True, max_length=20, null=True, verbose_name='new status')),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='camera.camera', verbose_name='camera')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='camera_actions', to=settings.AUTH_USER_MODEL, verbose_name='performed by')),
            ],
            options={
                'verbose_name': 'Camera Action Log',
                'verbose_name_plural': 'Camera Action Logs',
            },
        ),
        migrations.AddIndex(
            model_name='camera',
            index=models.Index(fields=['company', 'status'], name='camera_came_company_85e1b7_idx'),
        ),
        migrations.AddIndex(
            model_name='camera',
            index=models.Index(fields=['company', 'recording_status'], name='camera_came_company_0a8d38_idx'),
        ),
        migrations.AddIndex(
            model_name='cameraactionlog',
            index=models.Index(fields=['camera', 'timestamp'], name='camera_came_camera__cee700_idx'),
        ),
        migrations.AddIndex(
            model_name='cameraactionlog',
            index=models.Index(fields=['performed_by'], name='camera_came_perform_18cd32_idx'),
        ),
        migrations.AddIndex(
            model_name='cameraactionlog',
            index=models.Index(fields=['action', 'timestamp'], name='camera_came_action_27e99d_idx'),
        ),
        migrations.AddIndex(
            model_name='cameraactionlog',
            index=django.contrib.postgres.indexes.GinIndex(fields=['metadata'], name='camera_came_metadat_901230_gin'),
        ),
    ]
