# Generated by Django 4.2.22 on 2025-06-07 07:31

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Create Time')),
                ('modify_time', models.DateTimeField(auto_now=True, verbose_name='Modify Time')),
                ('name', models.CharField(max_length=255, verbose_name='Camera Name')),
                ('location', models.CharField(blank=True, max_length=255, null=True, verbose_name='Location')),
                ('ip_address', models.GenericIPAddressField(protocol='IPv4', unique=True, verbose_name='IP Address')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'ONLINE'), (1, 'OFFLINE')], db_index=True, verbose_name='status')),
                ('recording_status', models.PositiveSmallIntegerField(choices=[(0, 'Recording'), (1, 'Stopped')], db_index=True, verbose_name='recording status')),
                ('is_moved', models.BooleanField(db_index=True, default=False, verbose_name='is moved')),
            ],
            options={
                'verbose_name': 'Camera',
                'verbose_name_plural': 'Cameras',
            },
        ),
        migrations.CreateModel(
            name='CameraActionLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Create Time')),
                ('modify_time', models.DateTimeField(auto_now=True, verbose_name='Modify Time')),
                ('action', models.PositiveSmallIntegerField(choices=[(0, 'TURNED OFF'), (1, 'TURNED ON'), (2, 'MOVED'), (3, 'STARTED RECORDING'), (4, 'STOPPED RECORDING')], db_index=True, verbose_name='action')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='timestamp')),
                ('metadata', models.JSONField(default=dict, verbose_name='metadata')),
                ('old_status', models.CharField(blank=True, max_length=20, null=True, verbose_name='old status')),
                ('new_status', models.CharField(blank=True, max_length=20, null=True, verbose_name='new status')),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='camera.camera', verbose_name='camera')),
            ],
            options={
                'verbose_name': 'Camera Action Log',
                'verbose_name_plural': 'Camera Action Logs',
            },
        ),
    ]
