# Generated by Django 4.2.22 on 2025-06-07 07:31

from django.conf import settings
import django.contrib.postgres.indexes
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('camera', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cameraactionlog',
            name='performed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='camera_actions', to=settings.AUTH_USER_MODEL, verbose_name='performed by'),
        ),
        migrations.AddField(
            model_name='camera',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cameras', to='users.company', verbose_name='Company'),
        ),
        migrations.AddIndex(
            model_name='cameraactionlog',
            index=models.Index(fields=['camera', 'timestamp'], name='camera_came_camera__cee700_idx'),
        ),
        migrations.AddIndex(
            model_name='cameraactionlog',
            index=models.Index(fields=['performed_by'], name='camera_came_perform_18cd32_idx'),
        ),
        migrations.AddIndex(
            model_name='cameraactionlog',
            index=models.Index(fields=['action', 'timestamp'], name='camera_came_action_27e99d_idx'),
        ),
        migrations.AddIndex(
            model_name='cameraactionlog',
            index=django.contrib.postgres.indexes.GinIndex(fields=['metadata'], name='camera_came_metadat_901230_gin'),
        ),
        migrations.AddIndex(
            model_name='camera',
            index=models.Index(fields=['company', 'status'], name='camera_came_company_85e1b7_idx'),
        ),
        migrations.AddIndex(
            model_name='camera',
            index=models.Index(fields=['company', 'recording_status'], name='camera_came_company_0a8d38_idx'),
        ),
    ]
