# Generated by Django 5.2.2 on 2025-06-06 09:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(db_index=True, help_text='Iranian mobile number starting with +989 or 00989 followed by 8 digits', max_length=12, unique=True, validators=[django.core.validators.RegexValidator(regex='^(\\+989|00989)\\d{8}$')], verbose_name='phone number'),
        ),
    ]
