# Generated by Django 5.2.2 on 2025-06-06 11:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(db_index=True, help_text='Iranian mobile number starting with +989 or 00989 followed by 8 digits', max_length=14, unique=True, validators=[django.core.validators.RegexValidator(regex='^(\\+98|0)?9\\d{9}$')], verbose_name='phone number'),
        ),
    ]
